### ISSUE TITLE
version is not satisfied

### ISSUE THREAD

**Issue by lshowway** [studio-ousia/luke#102]
The recommend pytorch==1.2.0, the recommond transformers==2.4.1, but luke exists in the master branch of transformers. So I install transformers==4.13.0.dev0, but pytorch>=1.5.0 is required.

**Comment by ikuyamada** [comment]
The requirements.txt file was outdated. I've fixed this problem by updating the file to reflect the changes in pyproject.toml.

**Comment by lshowway** [comment]
@ikuyamada I solve the problem by setting transformers==4.13.dev0 and torch==1.5.0
