### ISSUE TITLE
The meaning of entity_ids=[1, 0] when finetune OpenEntity dataset

### ISSUE THREAD

**Issue by lshowway** [studio-ousia/luke#103]
I am runing the fine-tuning process on OpenEntity, but I can not understand well the code below, why `entity_ids=[1, 0]`
`entity_ids = [1, 0]
        entity_attention_mask = [1, 0]
        entity_segment_ids = [0, 0]
        entity_position_ids = list(range(mention_start, mention_end))[:max_mention_length]
        entity_position_ids += [-1] * (max_mention_length - mention_end + mention_start)
        entity_position_ids = [entity_position_ids, [-1] * max_mention_length]  `

**Comment by ikuyamada** [comment]
I am not sure if I understand your question correctly, I use `entity_ids = [1, 0]` instead of `entity_ids = [1]` to fix an error occurred during the training with the APEX library. I did not investigate why the error happened.

**Comment by lshowway** [comment]
@ikuyamada `entity_ids = [1]`, I can not understand what it means. Does it represent the `e` in the lower right corner in Fig. 1 (Architecture of LUKE). Besides, entities are also appended to input text during the fine-tuning phase?

**Comment by ikuyamada** [comment]
As explained in the paper, entities are treated as independent tokens in LUKE. entity_ids represent the ID of the entities in the input text.

**Comment by lshowway** [comment]
@ikuyamada Thanks for your response. I know LUKE is designed for entity-related tasks, but could it be applied to general tasks, such as GLUE benchemarks?

**Comment by ikuyamada** [comment]
LUKE can be used for general NLP tasks by inputting subword IDs similar to other models such as BERT. Also, you may be able to gain extra performance improvement by adding entity IDs, but this requires an external entity linking software.

**Comment by lshowway** [comment]
I want to fine-tune released LUCK checkpoints on a sentence-pair classification task, i.e., the input is: sentence A, sentence B, the output is in {0, 1}. Is the following setting right?
The first one:
**model architecture**: roberta-base
**checkpoints**: LUKE released
**input format**: CLS+sentenceA+SEP+sentenceB+SEP+entityA+entityB(entityA and entityB are linked from sentenceA and sentenceB by entity linking software, it may not exist)
**question**: will the entity-aware self-attention be modified?

The second one:
**model architecture**: roberta-base
**checkpoints**: LUKE released
**input format**: CLS+sentenceA+SEP+sentenceB+SEP
**question**: could it be seen entity-related information enhanced results? Do the entity-aware self-attention need to be modified, or general self-attention is adopted?

**Comment by lshowway** [comment]
@ikuyamada I tested LUKE on SST2 dataset from GLUE, and compared its performance with `roberta-base`. Every parameter is set the same except the loaded checkpoints, however, the results show no gains. I am not sure if there are wrong settings or LUKE is not suitable for general NLP tasks?

**Comment by ikuyamada** [comment]
Since LUKE is designed to solve entity-related tasks that typically require real-world knowledge, we did not test LUKE on sentence classification tasks. However, as our entity embeddings contain rich information that may be useful for general NLP tasks, LUKE can achieve enhanced results on these tasks than RoBERTa.

**Comment by lshowway** [comment]
@ikuyamada So, for the following operation, where should be optimized? Since there is no explicit entity in `SST2`, do I need to extract entities by entity linking tool? If the entities are extracted, what should I do to include them?

> I want to fine-tune released LUCK checkpoints on a sentence-pair classification task, i.e., the input is: sentence A, sentence B, the output is in {0, 1}. Is the following setting right? The first one: **model architecture**: roberta-base **checkpoints**: LUKE released **input format**: CLS+sentenceA+SEP+sentenceB+SEP+entityA+entityB(entityA and entityB are linked from sentenceA and sentenceB by entity linking software, it may not exist) **question**: will the entity-aware self-attention be modified?
> 
> The second one: **model architecture**: roberta-base **checkpoints**: LUKE released **input format**: CLS+sentenceA+SEP+sentenceB+SEP **question**: could it be seen entity-related information enhanced results? Do the entity-aware self-attention need to be modified, or general self-attention is adopted?

**Comment by ikuyamada** [comment]
Unfortunately, since I did not test that, I do not have an answer if adding entities to the input sequence improve the performance. Regarding how to construct entity sequence, please refer to the [reading comprehension example](https://github.com/studio-ousia/luke/tree/master/examples/reading_comprehension).
