### ISSUE TITLE
Unable to fine-tune relation classification models using AllenNLP examples

### ISSUE THREAD

**Issue by fillipefbr** [studio-ousia/luke#107]
Hi,

I can't fine-tune the models for relation classification using the provided [examples for AllenNLP](https://github.com/studio-ousia/luke/tree/master/examples_allennlp/relation_classification), I always get a generic _FileNotFoundError_.

Besides, I noticed that the model imported in [transformers_luke.jsonnet](https://github.com/studio-ousia/luke/blob/master/examples_allennlp/relation_classification/configs/transformers_luke.jsonnet) is defined as **"lib/transformers_model_luke.jsonnet"** but the actual file name is **"lib/transformers_luke_model.jsonnet"** (**"model"** and **"luke"** are inverted). However, changing this setting doesn't solve the problem. Could you check if the examples are still working? Am I missing something?

Thank you!

**Comment by Ryou0634** [comment]
Hi, thank you for reporting this.
Some paths in the code were from an old version, which caused the error.
I've just fixed the code and READMEs, so please pull the latest code from the master branch, and then run the commands again.
