### ISSUE TITLE
what is the pre-training corpus in LUKE.

### ISSUE THREAD

**Issue by lshowway** [studio-ousia/luke#112]
Thanks for your work.
According to the paper, the pertaining corpus is Wikipedia with entity annotations.
So, is the corpus the same as NTEE? Or, could you provide the link or something else for me to get more about this corpus?

Thanks.

**Comment by ikuyamada** [comment]
Hi @lshowway,

The pretraining corpus is created using a Wikipedia dump which can be downloaded [here](https://dumps.wikimedia.org/). The dump file is preprocessed using the [`build_wikipedia_pretraining_dataset` command](https://github.com/studio-ousia/luke/blob/master/luke/pretraining/dataset.py#L46). The `dump_db_file` can be built using [`build-dump-db` command](https://wikipedia2vec.github.io/wikipedia2vec/commands/#building-dump-database) of Wikipedia2Vec.
