### ISSUE TITLE
Entity distribution problem in pretraining dataset

### ISSUE THREAD

**Issue by dalek-who** [studio-ousia/luke#119]
Hello, as shown in your statistics of the entity frequency, entities in Wikipedia follow a Zipf distribution. Do you deal with the frequency inbalance problem in pretraining dataset (e.g. down-sampling for head entities, up-sampling for tail entities, etc) ? Or you directly use whole Wikipedia for pretraining without special processing?

**Comment by ikuyamada** [comment]
Hi @dalek-who,
We did not do anything to deal with the imbalance of entities.
