### ISSUE TITLE
Entity vocabulary for pretrained models?

### ISSUE THREAD

**Issue by jdeitelzweig** [studio-ousia/luke#121]
Is there somewhere I can find the list of 500K entities used for the pre-training of LUKE-base?

**Comment by ikuyamada** [comment]
Hi @jdeitelzweig, [the model archive file](https://github.com/studio-ousia/luke#released-models) contains the entity vocabulary file (`entity_vocab.tsv`). Also, the JSON version of the file can be directly downloaded from [this page](https://huggingface.co/studio-ousia/luke-base/tree/main).

**Comment by jdeitelzweig** [comment]
Great, thank you so much!
