### ISSUE TITLE
DatasetProcessor doesn't use all attributes present in TACRED

### ISSUE THREAD

**Issue by aakashb95** [studio-ousia/luke#127]
I read through the [reader](https://github.com/studio-ousia/luke/blob/ed965b727b8d887230cd49d30ac63440a77e1da0/examples/relation_classification/reader.py#L99) and legacy [utils](https://github.com/studio-ousia/luke/blob/ed965b727b8d887230cd49d30ac63440a77e1da0/examples/legacy/relation_classification/utils.py#L93) and found that 
```
'stanford_pos', 'stanford_ner', 'stanford_head', 'stanford_deprel'
```
are not used and not fed into the model. 
Is there any specific reason these are ignored?

**Comment by ikuyamada** [comment]
Hi @aakashb95,
As LUKE takes only words and entities as inputs, we do not use additional data such as part-of-speech and named entities.

**Comment by aakashb95** [comment]
Thanks. Just one follow-up question, If I label-encode the part-of-speech and named-entities and feed it into the model, theoretically, it should aid the model to make better predictions right? My assumption here is we are feeding more clues into the model. Is my thinking right? I will try it anyway and revert here :)

**Comment by ikuyamada** [comment]
Adding such data may improve the performance though, I think there is no straightforward way to add the data to the inputs of LUKE. Do you have any idea to add them as inputs?

**Comment by aakashb95** [comment]
I have the same doubt, and it is not straight-forward so I am exploring options..

As of now, I think I might try the following approach by adding the data to vocab:
https://github.com/huggingface/transformers/issues/1413#issuecomment-538083512

Or figure out a way to use the data like it has been done [here](https://github.com/yuhaozhang/tacred-relation)

Please do suggest your thoughts as well.

**Comment by ikuyamada** [comment]
Thanks for your reply!

I think this is an interesting direction to investigate. However, since recent language models generally achieve excellent performance for predicting linguistic features such as part-of-speech and NER, such linguistic features may easily be inferred from the input text inside the model.

**Comment by aakashb95** [comment]
> such linguistic features may easily be inferred from the input text inside the model.

Agreed. 
I will post my findings once I am able to achieve this. Thanks for your inputs :)
