### ISSUE TITLE
"IndexError" during Luke RE fine tuning.

### ISSUE THREAD

**Issue by elonmusk-01** [studio-ousia/luke#129]
Hi, @ikuyamada I am using the same solution I have used for many other successful RE tasks. This time doing the same steps (Creating TACRED like dataset) I am getting index errors after training goes to 5-6%. Can you please spot what's wrong this time?
![Screenshot from 2022-04-22 12-11-51](https://user-images.githubusercontent.com/98889224/164625794-e17c61b1-97bb-4ae4-ad65-f4412060565b.png)

**Comment by ikuyamada** [comment]
I think the error is originally raised from [here](https://github.com/huggingface/transformers/blob/a315988baeddd64da3eb4f030ca804ef92a73d1f/src/transformers/models/roberta/modeling_roberta.py#L133) and `position_ids` created [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/roberta/modeling_roberta.py#L105) may contain invalid values. Maybe the length of `word_ids` is longer than the length limit (i.e., 512 subwords)?

**Comment by elonmusk-01** [comment]
Thanks, @ikuyamada. Looks like I have to look into the dataset and Not the code or hyperparameters as solution works for similar datasets.

**Comment by elonmusk-01** [comment]
Anyways does it take care of spelling mistakes if present in datasets or if some tokens appear to be as merged tokens in the dataset? Do these unknown tokens have an effect on failed training?

**Comment by ikuyamada** [comment]
Misspellings do not generally cause training failure. It should be taken care of by the subword tokenization method.

**Comment by elonmusk-01** [comment]
I am using OCR for text extraction before performing annotations. OCR output sometimes extracts signatures or doubtful words as these words don't exist in real vocabulary. So I wonder if these words are not present in model vocabulary chances are there will not be a corresponding ID for that word which may cause of index error. Can it be the case?

**Comment by ikuyamada** [comment]
As mentioned in #118, we do not provide technical support for arbitrary downstream datasets. As this issue is clearly not related to our research or reproduction of our experiments, please resolve the issue by yourself.
