### ISSUE TITLE
Reproducing different ED models,  local and global

### ISSUE THREAD

**Issue by bennigeir** [studio-ousia/luke#130]
Hi,

In your paper [Global Entity Disambiguation with BERT](https://arxiv.org/pdf/1909.00426.pdf) you report results from confidence-order, natural-order, and local context. Using your code, I am able to use `--context-entity-selection-order` to reproduce results for confidence-order and natural-order.
How do I reproduce results for **local**?

**Comment by bennigeir** [comment]
Is it the `"--use-context-entities/--no-context-entities"`?

**Comment by ikuyamada** [comment]
Hi @bennigeir,

Yes, `--no-context-entities` mode does not use context entities, which is equivalent to the local model.

**Comment by bennigeir** [comment]
Thank you @ikuyamada for confirming
