### ISSUE TITLE
Have LUKE been tested on FIGER dataset?

### ISSUE THREAD

**Issue by lshowway** [studio-ousia/luke#133]
FIGER dataset is a entity typing dataset, similar to OpenEntity but with 2  million training samples. I wander have you tested LUKE on this dataset?
I just change the date_dir from `../data/OpenEntity` to `../data/FIGER`，but I can not get an expected results, could you give me some advice?

**Comment by Ryou0634** [comment]
Hi @lshowway.
I don't think we have tried the FIGER dataset.

If you want to try a different dataset and it has a data format different from OpenEntity, you need to modify the reader code accordingly.
https://github.com/studio-ousia/luke/blob/eff5d0ae528c544aa1d6e7b51bfcd76992d266bf/examples/legacy/entity_typing/utils.py#L40

**Comment by lshowway** [comment]
@Ryou0634 Thank you very much.
FIGER has the same data format as OpenEntity, but it has 2 million samples, I just not sure how to set its batch size. Since the batch size on OpenEntity is 4, but it is too small on FIGER.

**Comment by lshowway** [comment]
@Ryou0634 Thanks for your detailed reply, it really solves my problems.
