### ISSUE TITLE
Results reported in the paper?

### ISSUE THREAD

**Issue by lshowway** [studio-ousia/luke#135]
Thanks for your solid work.

Are the results reported in the paper based on allennlp or [huggingface](https://github.com/studio-ousia/luke/tree/master/examples)?

I finetune LUKE on `OpenEntity` and `TACRED` dataset, with commands and code in [legacy](https://github.com/studio-ousia/luke/tree/master/examples/legacy)， but reduce the `max_seq_length` from 512 to 256 to avoid OOM. I repeat it more than five times with different seeds, and I got the average results of `77.6 `and `71.7`, respectively, while the reported results are `78.2` and `72.7`. 

Is this normal?

**Comment by Ryou0634** [comment]
I think that your result is within a reasonable range of performance fluctuation.

Although you changed `max_seq_length` from 512 to 256, that does not make a large difference on these datasets, where typical input sequence lengths are not so long.

Note that the paper reports the best performance of the model.
So if you take the average of the scores, it would be definitely lower than the highest score.
