### ISSUE TITLE
LUKE Large Finetuning Duration for NER

### ISSUE THREAD

**Issue by taghreed34** [studio-ousia/luke#138]
Hello there, 

I'm trying to finetune LUKE large for NER task using data with conll format from multiple sources including conll2003 itself, I've combined them together. The training is being done on Google Colab GPU, but it takes so long to finish a single batch, it took about 2 hours to train on just 2 batches with a batch size of 2, is this expected? And if not, why does this happen?

Thanks in advance

**Comment by taghreed34** [comment]
> Hi,
> 
> A single batch taking an hour sounds very unusual. Is GPU properly enabled? But it seems too long even with CPU... I suspect that it has something to do with the setup of Google Colab GPU but have no idea about what is going on there.
Yes the GPU is enabled, or the training task wouldn't have started from the beginning, it would have raise an error. But anyways I changed runtime type to GPU before running the notebook. Do I misunderstand something?

**Comment by taghreed34** [comment]
>

**Comment by taghreed34** [comment]
> 

Yes the GPU is enabled, or the training task wouldn't have started from the beginning, it would have raise an error. But anyways I changed runtime type to GPU before running the notebook. Do I misunderstand something?

**Comment by Ryou0634** [comment]
OK, could you share the notebook or the code snippet if possible?

**Comment by Ryou0634** [comment]
I tried running the training on Google Colab myself and with my code and data, I observed no problems.
I recommend installing the dependency via `poetry` like this.

```
!pip install -q --pre poetry
!poetry --version
!git clone https://github.com/studio-ousia/luke.git
cd luke
!poetry install
```

Just using `pip` can install the wrong versions of the libraries.


This is my notebook for reference (place the data as necessary).
https://colab.research.google.com/drive/1r6YJaMHRgfOCVhQ8vDABvcYct1-Od7KH?usp=sharing

**Comment by Ryou0634** [comment]
Does `poetry install` seem successful?
If so, how about running `poetry run allennlp train ...`?

**Comment by taghreed34** [comment]
Not for all packages, there are some of them with a "pending", "downloading" or "say 40%".
@Ryou0634

**Comment by taghreed34** [comment]
Okay I'll do that as soon as possible.

Thank you so much for your time and effort.
