### ISSUE TITLE
Hugging Face support for Entity Disambiguation 

### ISSUE THREAD

**Issue by mitchell-cody** [studio-ousia/luke#140]
First of all - exciting work with the model and codebase!

Are there plans to support the Entity Disambiguation model in Hugging Face?

If not, is there a way I can inherit the current Hugging Face LUKE model and modify methods for Entity Disambiguation?  Thank you in advance.

**Comment by JulesBelveze** [comment]
Hey @mitchell-cody did you get any info on this?
