### ISSUE TITLE
LUKE on custom datasets for NER 

### ISSUE THREAD

**Issue by Dimiftb** [studio-ousia/luke#144]
Hi there

I'm wondering if you're planning to release instructions on how to fine-tune LUKE on custom datasets such as [SciERC](http://nlp.cs.washington.edu/sciIE/) with different entity types? 

Thanks.

**Comment by Ryou0634** [comment]
Hi,

Although we cannot prepare instructions for each dataset, we have some recommendations for fine-tuning with custom datasets.

As our code is based on more generic NLP libraries such as `allennlp` or `transformers`, probably it would be the easiest to modify their example code to achieve your goal.

For example, if you want to experiment with the SciERC dataset and decided to use our `allennlp` code, all you have to do is modifying the `_read()` function [here](https://github.com/studio-ousia/luke/blob/master/examples/ner/reader.py). You can also refer to [the tutorial or guide of allennlp](https://docs.allennlp.org/main/) as necessary.

Hope this helps : )
