### ISSUE TITLE
Distilled Luke models and Pretraining of Lite Models

### ISSUE THREAD

**Issue by luffycodes** [studio-ousia/luke#154]
Hello,

Just curious to know if there are any distilled Luke models as well?

Also, what is the procedure to train the lite models? Does one just not the stage 1 training and skip directly to stage 2?

Thanks in advance,

**Comment by Ryou0634** [comment]
Unfortunately, we don't have distilled LUKE models.

>Also, what is the procedure to train the lite models? Does one just not the stage 1 training and skip directly to stage 2?
The lite models come from the original model, so they are not newly pretrained.
The lite models are just the LUKE model only with special entity embeddings (such as `[MASK]`) to reduce the memory footprint when you don't need so many entity embeddings.
