### ISSUE TITLE
Pipeline NER and ED modules

### ISSUE THREAD

**Issue by gabrielandrade2** [studio-ousia/luke#158]
Hello,

I was recently trying an Entity Linking pipeline for CoNLL2003 dataset using LUKE by executing the NER module to get the entity spans and then running the ED module, so I could get the reference to the Wikipedia link. Basically, I want to use the results from LUKE's NER model in the ED module somehow.

However, I cannot understand how the dataset file used in ED example page (https://github.com/studio-ousia/luke/tree/master/examples/entity_disambiguation) was created, more specifically, how the candidates were generated.
I don't see any code designed for that in the repository.

Is there some step that I am missing here? Or do I need some external code to generate the candidates for ED?

**Comment by ikuyamada** [comment]
Hi @gabrielandrade2,

Thanks for your question! For fair comparison with past models, our ED model uses the existing dataset with predefined entity candidates proposed in a [past work](https://arxiv.org/abs/1704.04920) and is available [here](https://github.com/octavian-ganea/deep-ed). Please refer to the paper for its details.
