### ISSUE TITLE
Script from huggingface to allennlp model

### ISSUE THREAD

**Issue by luffycodes** [studio-ousia/luke#159]
Hello, 

Is there a script to convert a luke huggingface model to allennlp model since finetuning scripts are in allennlp.

Any leads are welcome :)

**Comment by Ryou0634** [comment]
We are integrating the huggingface LUKE models into allennlp through this class.
[examples/utils/embedders/transformers_luke_embedder.py](https://github.com/studio-ousia/luke/blob/master/examples/utils/embedders/transformers_luke_embedder.py)

This embedder class is used throughout the downstream allennlp models in this repo.
You can specify the pretrained model name in the `model_name`.
