### ISSUE TITLE
Languages mLUKE was trained on?

### ISSUE THREAD

**Issue by sethfarns-strider** [studio-ousia/luke#180]
The paper indicates that mLUKE was trained on 24 languages, but I haven't been able to find that list anywhere. I do see it looks like 15 languages referenced in the experiment results in the paper, but that still leaves another 9. Could you tell me what those 24 languages are, or point me to where that information is located? Thanks

**Comment by ryokan0123** [comment]
Hi, thank you for your interest.
The full list of the languages is buried in the paper's Appendix.
Here's a screenshot of it:

<img width="753" alt="スクリーンショット 2023-10-06 0 05 49" src="https://github.com/studio-ousia/luke/assets/17979572/376d25bc-7ff6-4152-af98-7c2367381a96">

I hope this helps!

**Comment by sethfarns-strider** [comment]
Oh thanks! I don't know why I couldn't see that..
