### ISSUE TITLE
releasing running steps and pre-trained model

### ISSUE THREAD

**Issue by yifding** [studio-ousia/luke#20]
Really great work~
By injecting entity linking as a pre-train task with masked-language-model task, LUKE obtained great performance than previous BERT related model. 
Was wondering when the running steps, evaluation parts and pre-trained models are going to be released?

**Comment by ikuyamada** [comment]
Hi! I am currently working on another project, but will work on this repository soon. I will release the README before the EMNLP conference (November 16th).

**Comment by yifding** [comment]
Thanks for your response, close the issue now.
