### ISSUE TITLE
Entity Disambiguation Supporting Files

### ISSUE THREAD

**Issue by LithiumH** [studio-ousia/luke#22]
I saw that there is a folder for entity disambiguation but it seems to require more files such as the "person names" file. Could you add some instructions on how to run the entity disambiguation system please? Thanks

**Comment by ikuyamada** [comment]
Thank you for creating an issue. Although the code is included in this repository, we are not ready to release this. The current code requires the pretrained weights based on BERT, which has not been released yet.

**Comment by LithiumH** [comment]
Thanks for replying. Looking forward for the code release

**Comment by ikuyamada** [comment]
Hi @LithiumH,
I've just released the code and model checkpoint file [here](https://github.com/studio-ousia/luke/tree/master/examples/entity_disambiguation).
