### ISSUE TITLE
Train on dev for final rrsult

### ISSUE THREAD

**Issue by stefan-it** [studio-ousia/luke#24]
Hi @ikuyamada,

just a question regarding to training on development dataset:

In the example code the parameter is set to `True`:

https://github.com/studio-ousia/luke/blob/9323b216dd5f72b61545bc4133f7709fd19bfa95/examples/ner/main.py#L42

Did you also train on development dataset for the final paper result :thinking: 

Thanks and best,

Stefan

**Comment by ikuyamada** [comment]
Hi @stefan-it,

We do not use the development set in the experiment reported in the paper. Also, the default value of `--train-on-dev-set` parameter is `False`. We do not observe clear improvement when enabling this parameter.

Thanks,
Ikuya

**Comment by stefan-it** [comment]
Oh, is misinterpret the `is_flag` parameter 🙈

Thanks for your answer :hugs:
