### ISSUE TITLE
cannot import name 'BertLayerNorm' from 'transformers.modeling_bert'

### ISSUE THREAD

**Issue by lijiayi980130** [studio-ousia/luke#26]
cannot import name 'BertLayerNorm' from 'transformers.modeling_bert'

**Comment by ikuyamada** [comment]
Hi, did you follow the instructions available in README when installing LUKE?

**Comment by lijiayi980130** [comment]
I want to know if  I git clone luke，Did I still need to use poetry install?
and I find "transformers.modeling_bert” don't have "BertLayerNorm" class, I don't know why

**Comment by ikuyamada** [comment]
You need to install required packages by following instructions on README.
Furthermore, `transformers.modeling_bert` does contain `BertLayerNorm` class.
https://github.com/huggingface/transformers/blob/v2.11.0/src/transformers/modeling_bert.py#L141
