### ISSUE TITLE
Base size model

### ISSUE THREAD

**Issue by YeDeming** [studio-ousia/luke#27]
Hi,

Thanks for releasing the great code and model. Could you plan to release the roberta-base size model to meet low computation resource scenario?

Best
Deming

**Comment by ikuyamada** [comment]
Hi, We have a plan to release base size model in the near future, but have not decided the release date.

Thanks.

**Comment by ikuyamada** [comment]
I've just uploaded the base model of LUKE. Please refer to README for its details.
