### ISSUE TITLE
Wiki data for pretraining

### ISSUE THREAD

**Issue by yzhangcs** [studio-ousia/luke#28]
Hi, I'm very interested in your nice work and planning to reproduce the model results.
Could you please provide the download link of the wiki data for LUKE pretraining? 
Thanks in advance.

**Comment by ikuyamada** [comment]
Hi, Thank you for your interest to our paper. 
The Wikipedia dump file used in our pretraining (`enwiki-20181220-pages-articles.xml.bz2`) can be obtained from the archive.org: https://archive.org/download/enwiki-20181220

**Comment by yzhangcs** [comment]
Thank you :)
