### ISSUE TITLE
Model training duration

### ISSUE THREAD

**Issue by aschmu** [studio-ousia/luke#31]
Hello ! Great paper and really cool idea overall ! 
Could you please report how long pretraining took (with the number of gpus) as well as training duration for the NER task on Conll 2003 ?

**Comment by ikuyamada** [comment]
As reported in [our paper](https://arxiv.org/abs/2010.01057), the pretraining was conducted using 16 NVIDIA Tesla V100 GPUs and took approximately 30 days (Appendix A). The training duration of CoNLL-2003 NER was 203 minutes (Table 11).
