### ISSUE TITLE
Results of ner is not displayed in logs

### ISSUE THREAD

**Issue by Riroaki** [studio-ousia/luke#36]
Hi, a small bug here: the results are not rendered in logging info
https://github.com/studio-ousia/luke/blob/9323b216dd5f72b61545bc4133f7709fd19bfa95/examples/ner/main.py#L93

This line should be `logger.info("Results: %s" % json.dumps(results, indent=2, sort_keys=True))` right?^_^

**Comment by ikuyamada** [comment]
Hi,
I think this is not a bug. Please see the following URL:
https://docs.python.org/3/howto/logging.html#logging-variable-data

**Comment by Riroaki** [comment]
Oh, I think it's because I set the argument `no-eval` in training, the results are not calculated, and thus not displayed...
