### ISSUE TITLE
Fine-tuned models ckpts

### ISSUE THREAD

**Issue by KMnP** [studio-ousia/luke#39]
Thank you for the well-organized code and instructions!! I wonder if it is possible to get the fine-tuned models ckpts for the down-streaming tasks (e.g. TACRED, CoNLL-2013)?

**Comment by ikuyamada** [comment]
Hi,
I can provide fine-tuned checkpoint files, but the current code (in the `examples` directory) does not run correctly based on trained checkpoints. I will work on this issue soon.
I am sorry for the inconvenience.

**Comment by KMnP** [comment]
Thank you for your reply! I'm mainly looking for TACRED task.

**Comment by ikuyamada** [comment]
Hi,
I have uploaded the fine-tuned checkpoint files for all tasks and added their links to README.
Please let me know if there are any further issues.
