### ISSUE TITLE
Redirect entity titles in entity disambigution

### ISSUE THREAD

**Issue by horseee** [studio-ousia/luke#40]
Hi, nice work !
I am interested in how LUKE performs on Entity Disambigution tasks. However, I find there is a gap on the entity titles between these benchmark datasets and the pre-training wikipedia dump. And I find that there may be a redirect file
```
valid_titles = None
if wikipedia_titles_file:
    with open(wikipedia_titles_file) as f:
        valid_titles = frozenset([t.rstrip() for t in f])

redirects = {}
if wikipedia_redirects_file:
    with open(wikipedia_redirects_file) as f:
        for line in f:
            (src, dest) = line.rstrip().split("\t")
            redirects[src] = dest
```
Could you please share these files? Thanks a lot !

**Comment by ikuyamada** [comment]
Hi,
Thank you for creating the issue!

As also mentioned in #22, the entity disambiguation code is not ready to be used.
To avoid confusion, I removed the code from the master branch.

**Comment by ikuyamada** [comment]
Hi @horseee,
I've just released the code and model checkpoint file [here](https://github.com/studio-ousia/luke/tree/master/examples/entity_disambiguation).
