### ISSUE TITLE
Does the project support Chinese?

### ISSUE THREAD

**Issue by Single430** [studio-ousia/luke#42]
Really great work~
But recently I want to do ner and re tasks on the Chinese data set.
@ikuyamada

**Comment by ikuyamada** [comment]
Thanks! LUKE does not currently support Chinese. We are now planning to work on multi-lingual version of LUKE.

**Comment by Single430** [comment]
> Thanks! LUKE does not currently support Chinese. We are now planning to work on multi-lingual version of LUKE.

Thanks Reply!
Looking forward to your multi-lingual version of LUKE.
