### ISSUE TITLE
Benchmark on FewRel dataset

### ISSUE THREAD

**Issue by samru-rai** [studio-ousia/luke#44]
Let me start off my saying this that this is one of the cleanest repository from any published paper I have every seen. 

Standing ovation for the maintainers 👏👏👏👏👏👏

Now my question : Can we also provide instructions on fine-tuning and evaluating on [FewRel](https://github.com/thunlp/FewRel) data (Relation classification)? TacRED is hidden behind a paywall and has complicated procedures to obtain for any commercial usage.

**Comment by ikuyamada** [comment]
Thanks!😄
I do not currently have time to work on it, but it may be easy to support the FewRel dataset by adding the `convert_examples_to_features` function for the dataset.
https://github.com/studio-ousia/luke/blob/master/examples/relation_classification/utils.py#L107

**Comment by samru-rai** [comment]
You're welcome! Alright thank you for your quick response!
