### ISSUE TITLE
Unable to reproduce NER numbers using the released checkpoint

### ISSUE THREAD

**Issue by shivapk** [studio-ousia/luke#45]
Hi, i was trying to evaluate your NER checkpoint on CONLL2003 test set. I was getting close to 0.72F1. Did you by chance face this issue? I gave a try using the test sets from [here](https://github.com/synalp/NER/tree/master/corpus/CoNLL-2003) and [here.](https://github.com/mxhofer/Named-Entity-Recognition-BidirectionalLSTM-CNN-CoNLL/tree/master/data) Both evaluations have similar F1. Could someone please look into this issue. Thank you!

           precision    recall  f1-score   support

      PER     0.9639    0.4338    0.5984      1602
     MISC     0.8680    0.5720    0.6896       701
      LOC     0.9596    0.7407    0.8360      1666
      ORG     0.9418    0.5792    0.7173      1647
micro avg    0.9431     0.5848     0.7219       5616
macro avg   0.9442     0.5848     **0.7151**       5616

**Comment by ikuyamada** [comment]
Hi,
Thank you for creating the issue!
I ran the experiments again using the following command and successfully reproduced the results:

```bash
python -m examples.cli --model-file=luke_large_500k.tar.gz ner run --data-dir=data/conll_2003/ --checkpoint-file=pytorch_model.bin --no-train
[2021-01-16 16:07:43,699] [INFO] Output dir: exp_YawtNwDZ (cli@cli.py:78)
[2021-01-16 16:09:11,625] [INFO] Creating features from the dataset... (load_examples@main.py:185)
[2021-01-16 16:09:54,205] [INFO] Creating features from the dataset... (load_examples@main.py:185)
The number of labels: 51362
           precision    recall  f1-score   support

      ORG     0.9630    0.9702    0.9666      1341
      LOC     0.9777    0.9814    0.9795      1830
      PER     0.9831    0.9847    0.9839      1832
     MISC     0.9267    0.9136    0.9201       914

micro avg     0.9683    0.9694    0.9688      5917
macro avg     0.9682    0.9694    0.9688      5917

[2021-01-16 16:15:06,318] [INFO] Creating features from the dataset... (load_examples@main.py:185)
The number of labels: 46435
           precision    recall  f1-score   support

      ORG     0.9321    0.9496    0.9408      1647
      LOC     0.9559    0.9508    0.9534      1666
      PER     0.9689    0.9725    0.9707      1602
     MISC     0.8569    0.8716    0.8642       701

micro avg     0.9401    0.9468    0.9434      5616
macro avg     0.9403    0.9468    0.9435      5616

[2021-01-16 16:19:42,131] [INFO] Results: {
  "dev_f1": 0.9688370914618697,
  "dev_precision": 0.9682646860229575,
  "dev_recall": 0.9694101740747,
  "test_f1": 0.9433995741660753,
  "test_precision": 0.9400636492220651,
  "test_recall": 0.9467592592592593
} (run@main.py:97)
```

I also confirmed that the `eng.testb` dataset available [here](https://github.com/synalp/NER/tree/master/corpus/CoNLL-2003} is exactly the same as the one used in our experiments.

Did you install LUKE and its dependencies using `poetry install`? We only tested the code with library versions specified in the `poetry.lock` file, and the current code may have issues with dependent libraries with different versions than those specified in the file.

**Comment by shivapk** [comment]
Thanks for the prompt reply @ikuyamada. You are right, package version mismatch was the issue. using `poetry install `solved it. Also, if someone is try to evaluate NER on custom dataset please make sure to set `max-mention-length` limit based on your dataset https://github.com/studio-ousia/luke/blob/master/examples/ner/main.py#L37.
