### ISSUE TITLE
Is there an easy way to perform relationship inference on a single example?

### ISSUE THREAD

**Issue by prematurelyoptimized** [studio-ousia/luke#46]
The results from the EMNLP paper look really promising, so I would like to manually try the model on a couple examples of my own data.  Is there an easy way to do this?  I can easily run my data through spaCy to find entities, but do I need to dump each example to a file in the TACRED format, then run the command line script, etc?

**Comment by ikuyamada** [comment]
Yes, the easiest way without modifying the current code is to create input data in the TACRED format, and feed it to the model. However, as the code is compact, you can easily modify the code to do what you want.
https://github.com/studio-ousia/luke/tree/master/examples/relation_classification
