### ISSUE TITLE
two question about CONLL2003

### ISSUE THREAD

**Issue by MingHong1019** [studio-ousia/luke#48]
I get 94.3 f1 value in the test dataset of CONLL2003. But I have some question:
1.  the label '' O '' don't participate in the evaluation process right? 
2. how to deal with the prefix of label, such as 'B-PER' and 'I-PER' since I can only see the  result of 'PER' ?
Thanks a lot~

**Comment by ikuyamada** [comment]
We classify each possible span in the target text into the target classes (e.g., PERSON) or the NIL class. It is possible to automatically generate the output label sequence with prefix (B, I, or O) based on the classified spans.
For example, given a 10 words with classified spans `(2, 4)` as a PERSON and `(4, 6)` as a PERSON, and `(8, 9)` as a LOCATION, the output sequence in the IOB1 format is: `[O, O, I-PERSON, I-PERSON, B-PERSON, B-PERSON, O, O, I-LOCATION, O]`.

**Comment by MingHong1019** [comment]
And then calculate f1 value according to output sequence and real label sequence?  Then why the print only shows the label with out IOB1 format?

**Comment by ikuyamada** [comment]
What does "the print" refer to? If you refer to the table, it is generated by the `classification_report` function of the [seqeval library](https://github.com/chakki-works/seqeval) with the predicted sequence and gold-standard label sequence as inputs.
https://github.com/studio-ousia/luke/blob/master/examples/ner/main.py#L159

**Comment by MingHong1019** [comment]
yeap, thanks a lot!
