### ISSUE TITLE
ONNX the model?

### ISSUE THREAD

**Issue by samru-rai** [studio-ousia/luke#51]
The base `roberta-large` model is well, large. It takes a lot of GPU to use this model. Is it possible to ONNX it such that we can run it on CPU? 

I believe roberta is supported by ONNX but due to complicated nature of the Luke model, I found it difficult to just use the [instructions outlined](https://huggingface.co/transformers/serialization.html) by HF team.

**Comment by ikuyamada** [comment]
Hi,
I am sorry but we do not have any information regarding how to convert the LUKE model to the ONNX format.
