### ISSUE TITLE
The result of conll2003 

### ISSUE THREAD

**Issue by jinpeng01** [studio-ousia/luke#54]
Hello, what are your specific hyperparameters in the entity recognition task? I can’t reproduce the results on the paper. Thank you so much.

**Comment by ikuyamada** [comment]
Hi,
I used the same hyper-parameters as those reported in the paper. Did you fail to reproduce the results based on the trained checkpoint file?

**Comment by jinpeng01** [comment]
Yes, the checkpoint file fails to achieve the result reported on paper. Could you send your dataset  conll2003. Thanks so much.

**Comment by ikuyamada** [comment]
Hi,
This issue is related to this [past issue](https://github.com/studio-ousia/luke/issues/45).
Please refer to the issue and let me know if you still fail to reproduce the results.
