### ISSUE TITLE
Pretraining on multiple GPU's

### ISSUE THREAD

**Issue by asgerius** [studio-ousia/luke#55]
Hi

First off, thanks for the amazing work. However, I have some trouble getting pretraining to work on multiple GPU's.

I am trying to use the pretraining code for training LUKE in another language. To start pretraining, I run `python -m luke.cli pretrain` with the `--parallel` flag. On [this line](https://github.com/studio-ousia/luke/blob/master/luke/pretraining/train.py#L470), a command starting with `luke` is made, but this fails when given to `subprocess.Popen`. Does `luke` refer to something I need in my path, a shell script not in the repo, some result of `click`, or something entirely different?

**Comment by ikuyamada** [comment]
Hi,

The parallel pretraining uses `luke` command which is required to exist in the system path. The command should be created by poetry as specified in [this line](https://github.com/studio-ousia/luke/blob/master/pyproject.toml#L38).
Please confirm that the command is properly created by poetry.

**Comment by asgerius** [comment]
Ok, thanks a lot.

I have not been able to get `poetry` to work on my university's cluster, so I have used `pip` so far, which explains it. I will put some more work into getting `poetry` to work then.

**Comment by ikuyamada** [comment]
@asgerius  Poetry places the `luke` command in the `bin` directory in the virtual environment. The content of the file is as follows:

```
#!python
from luke.cli import cli

if __name__ == '__main__':
    cli()
```

**Comment by asgerius** [comment]
That seems pretty straightforward. I will give it a try. Thanks for the quick response

**Comment by ikuyamada** [comment]
Maybe it is easier to simply create the file instead of using poetry in your cluster :)

**Comment by svjan5** [comment]
Hi @asgerius and @ikuyamada, 
I am getting the same issue but unable to resolve it. Can you provide more details of the solution? 

thanks in advance!
