### ISSUE TITLE
No module named 'torch' after installing with Poetry

### ISSUE THREAD

**Issue by seanswyi** [studio-ousia/luke#59]
Hi. I ran RE with your code without installing LUKE using Poetry and wasn't able to reproduce the reported results. After searching around I found a similar closed issue here regarding NER and decided to install LUKE using Poetry.

After running `poetry install` and subsequently `poetry shell`, however, I get the import error for PyTorch despite already having downloaded it.

I tried running `poetry add torch` but it claims PyTorch is already present.

Is this normal, and would you by any chance have any idea how I should fix this? Thanks.

**Comment by ikuyamada** [comment]
Hi,

I think the `poetry install` command should install `torch`. It may be easier to use the `requirements.txt` by creating it using `poetry export`.

```
poetry export -f requirements.txt --output requirements.txt
```

**Comment by seanswyi** [comment]
Thanks, I'll give that a try.
