### ISSUE TITLE
Apex and Pyramid version question

### ISSUE THREAD

**Issue by seanswyi** [studio-ousia/luke#61]
Hi. May I ask what version of Apex and Pyramid you used when you ran your model? Right now my Apex version is 0.9.10.dev0 and Pyramid is 2.0.

Whenever I try to import Apex I get the following:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/luke/lib/python3.7/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
```

Judging by my impression that Apex isn't really actively maintained, I've tried downgrading Pyramid to a compatible version (i.e., > 1.1.2) but that returns a different error.

I'm just curious what versions you guys used in order to try and match that. Thanks.

**Comment by ikuyamada** [comment]
Hi,
Please refer to the README: https://github.com/studio-ousia/luke#reproducing-experimental-results

**Comment by seanswyi** [comment]
Ah my bad, must have missed it. Thanks!
