### ISSUE TITLE
Question Regarding Entity Embeddings

### ISSUE THREAD

**Issue by seanswyi** [studio-ousia/luke#62]
Hi. I just had a question regarding the entity embeddings used in the model. Specifically, I'm trying to run the LUKE model on relation extraction.

I've noticed that the `entity_vocab_size` is set to 3, and the `entity_ids` are hard-coded to be `[1, 2]`. I'm just curious why this might be? My impression for `[1, 2]` is that the TACRED dataset assumes that there are only two entities in a given text and therefore the entity IDs would be the same, but please let me know if I'm incorrect.

Also, do you think it would be possible to run LUKE on datasets where a data sample may have a variable number of entity mentions? My impression is that the implementation wouldn't be straightforward because I'm getting the feeling that utilizing the `EntityEmbeddings` may be a bit tricky.

Thanks for your help.

**Comment by ikuyamada** [comment]
Hi, 

> I've noticed that the entity_vocab_size is set to 3, and the entity_ids are hard-coded to be [1, 2]. I'm just curious why this might be? My impression for [1, 2] is that the TACRED dataset assumes that there are only two entities in a given text and therefore the entity IDs would be the same, but please let me know if I'm incorrect.

This is correct. Entity with ID 1 and that with ID 2 correspond to head and tail entities, respectively.

> Also, do you think it would be possible to run LUKE on datasets where a data sample may have a variable number of entity mentions? My impression is that the implementation wouldn't be straightforward because I'm getting the feeling that utilizing the EntityEmbeddings may be a bit tricky.

I think it is possible to compute representations of the variable number of entity mentions in a straightforward way by inputting corresponding entity sequence. The example code of entity_span_qa and ner handles a variable number of entity mentions. If your task is relation classification, the code to compute loss between entity pairs may be a bit challenging.

**Comment by seanswyi** [comment]
Sorry for the late reply, and yes I believe that you're correct. Thanks!
