### ISSUE TITLE
How should I run experiments without entity embeddings (i.e., ablation study)?

### ISSUE THREAD

**Issue by seanswyi** [studio-ousia/luke#65]
Hi. I'm trying to reimpement the ablation study regarding the entity inputs as was shown in section 5.1 and am wondering how you did it. Did you simply set the relevant variables (i.e., `entity_hidden_states`) to 0, or is there some other technique that you used?

**Edit**

After closer inspection I've noticed in line 108 in `luke.mode.LukeModel` there's a `if entity_ids is not None` conditional statement. I'm under the impression that if I didn't want to use entity inputs, then I could simply set `entity_ids = None` when feeding the input into the model. Is my interpretation correct? Thanks.

**Comment by ikuyamada** [comment]
Hi, there are miltiple ways to do this, but setting entity_attention_mask==0 might be an easiest way.

**Comment by seanswyi** [comment]
Hmm that seems like a straightforward method worth trying. Thanks!
