### ISSUE TITLE
Two questions: 1.Release entity vocab's wikipedia pageid? 2. Does [mask] occupy bert's 512 input?

### ISSUE THREAD

**Issue by dalek-who** [studio-ousia/luke#67]
1. Right now, some titles in entity vocab can not align to a unique wikipedia paged or wikidata entity id: some are missing, and some titles refer to a same pageid. Can you release the mapping between entity vocab's title and wikipedia pageid / wikidata entity id?
2. It seems that [mask]s for span representation don't occupy bert's 512 input? For example, I have a sequence with 512 tokens, and I want to use LUKE to extract 10 spans, then I can input 512 tokens+10 [mask], rather than 502 tokens + 10 [mask]? (as long as [mask] position embedding is correctly aligned to the 10 spans?)

**Comment by ikuyamada** [comment]
Hi, thank you for opening the issue.

> Right now, some titles in entity vocab can not align to a unique wikipedia paged or wikidata entity id: some are missing, and some titles refer to a same pageid. Can you release the mapping between entity vocab's title and wikipedia pageid / wikidata entity id?

LUKE does not use `page_id` since entity titles can also be used as unique identifiers. To resolve entity titles to page ids, did you use the December 2018 version of Wikipedia dump? I think entity titles can be resolved to page ids without issues if you use the same Wikipedia dump as the one used to create the entity vocabulary.

> It seems that [mask]s for span representation don't occupy bert's 512 input? For example, I have a sequence with 512 tokens, and I want to use LUKE to extract 10 spans, then I can input 512 tokens+10 [mask], rather than 502 tokens + 10 [mask]? (as long as [mask] position embedding is correctly aligned to the 10 spans?)

Yes, LUKE takes two kinds of inputs: `word_ids` and `entity_ids` and there are corresponding two kinds of maximum lengths: `max_seq_length` and `max_entity_length`.

**Comment by dalek-who** [comment]
Hello, there are two dumps in December 2018: 20181201 and 20181220, which one?

**Comment by ikuyamada** [comment]
Thanks for the reply! I haven't noticed that there are two Wikipedia dumps. We used the December 20, 2018 version of Wikipedia dump.

**Comment by dalek-who** [comment]
Here is an aligned entity vocab, I align title with wikpedia pageid and wikidata entityid, wish you can release it with checkpoint. 
[aligned_entity_vocab.csv](https://github.com/studio-ousia/luke/files/6296329/aligned_entity_vocab.csv)
Alignment is an important and dirty work for real-world system, but entity titles are not stable. In some bad case, the historical wiki dump version is not available, and current version may also disappear in the future. So I advise entity researchers releasing aligned title-wikipedia_pageid/wikidata_entity id :)

**Comment by dalek-who** [comment]
Although I use your dump version, some entities still miss, fortunately, not too much:

175999	Railway speed record	99
230697	TBWA\Chiat\Day	76
304473	Romanian Footballer of the Year (Gazeta Sportu...	58
390345	Customs broker	45
397086	Indoor hockey	44
399981	Capaccio Paestum	44
419400	Institute of Race Relations (disambiguation)	42
478537	John Dunn (radio presenter)	36

**Comment by ikuyamada** [comment]
@dalek-who Thank you so much for sharing the data!!
As this is clearly useful for other researchers, I will add a link to this file to README.

Regarding the missing entities, I confirmed that the Wikipedia database directly built from the December 20, 2018 dump contains these entities. The database was built using `build-dump-db` command defined [here](https://github.com/studio-ousia/luke/blob/master/luke/cli.py#L46). I check the existence of each entity using the following commands:

```python
>>> from wikipedia2vec.dump_db import DumpDB
>>> db = DumpDB('enwiki_20181220_2.db')
>>> db.get_paragraphs('Railway speed record')[:3]
[<Paragraph Rocket sled that achieved Mach 8.5...>,
 <Paragraph An L0 Series trainset, holding the non-conventiona...>,
 <Paragraph TGV 4402 (operation V150) reaching 574.8 km/h (357...>]
```

I am not sure why, but it may need further investigation.

**Comment by dalek-who** [comment]
@ikuyamada Another personal request: can you provide a full entity counting result? Since entity vocab only contain about top 10% entity. (Even unaligned is ok).

**Comment by ikuyamada** [comment]
@dalek-who I uploaded the entity vocabulary file containing all entities with at least one inbound hyperlink [here](https://drive.google.com/file/d/1C9c07Y1yDUWcu0KRsglDK7aekd7YQ4JA/view?usp=sharing) :)

**Comment by dalek-who** [comment]
@ikuyamada Does count means how many mentions (anchor text) links to this entity in whole wikipedia? And as a result, if an entity is not mentioned, it's excluded out of the full vocab?

**Comment by dalek-who** [comment]
@ikuyamada Does "count" means how many mentions (anchor text) links to this entity in whole wikipedia? And as a result, if an entity is not mentioned, it's excluded out of the full vocab?

**Comment by ikuyamada** [comment]
@dalek-who Yes, the count represents the number of hyperlinks pointing to the entity, and an entity is excluded if there is no hyperlink.

**Comment by dalek-who** [comment]
@ikuyamada Do you specially deal with entity imbalance problem in pretraining ?

**Comment by ikuyamada** [comment]
@dalek-who No, similar to the BERT’s masked language model, we simply predict every entity from the all entities in the vocabulary during pretraining.
