### ISSUE TITLE
About the version of transformers

### ISSUE THREAD

**Issue by XY2323819551** [studio-ousia/luke#68]
Hi, respected authors

I want to know what version of transformers is used for this project.

I met some issues when I run the code, which said "ModuleNotFoundError: No module named 'transformers.modeling_bert“，and"ImportError: cannot import name 'BertLayerNorm'", something like this. So I guess it was because I used wrong version of transformers, which is 4.5.0. Thank you!

**Comment by ikuyamada** [comment]
Hi, thank you for opening the issue!
We used version 2.4.1 of the transformers library.
Please note that as mentioned in README, this repository uses Poetry as a package management system and the version of the library used in our experiments is written in the poetry.lock file.
https://github.com/studio-ousia/luke/blob/master/poetry.lock#L972

**Comment by XY2323819551** [comment]
I see that now, thank you very much!
