### ISSUE TITLE
"ModuleNotFoundError: No module named 'icu'" when I tried to run in Google Colab

### ISSUE THREAD

**Issue by rafidwiriz** [studio-ousia/luke#71]
Hi, ikuyamada.

I found your paper about LUKE, and I really interested to try them with another datasets. But, I have one error that confuses me when I tried to run it in Google Colab, which is `ModuleNotFoundError: No module named 'icu'`.

Here is what I already did so far to resolve the problem, but never got it resolved:

1. I already add two packages via Poetry, `poetry add pycld2 morfessor`, but the problem still there.
2. I tried to add `icu` package using `poetry add icu`, but it gave me new error `ImportError: cannot import name 'Locale' from 'icu' (/root/.cache/pypoetry/virtualenvs/luke-_5-nTlMy-py3.7/lib/python3.7/site-packages/icu/__init__.py)`.

If you pleased, I really need your assistance with this problem. Thank you.

Best regards,

Rafi

**Comment by ikuyamada** [comment]
Hi Rafi,

The `icu` module is defined in the `pyicu` package. The package is defined as an optional dependency in pyproject.toml (please see [here](https://github.com/studio-ousia/luke/blob/master/pyproject.toml#L34)).

I believe that the `icu` module is only required in the `ICUSentenceTokenizer` class defined [here](https://github.com/studio-ousia/luke/blob/master/luke/utils/sentence_tokenizer.py#L24). This class is not used when addressing downstream tasks.

**Comment by rafidwiriz** [comment]
Thanks for the reply.

Right now, I'm building pretrain model using another dataset using the instruction from #41, and I'm in the step of `build-wikipedia-pretraining-dataset`.

Update, I think I resolve this problem by installing `pyicu` via Pip3 inside Poetry shell: `pip3 install pyicu`. Thank you for your assistance. You can close this issue.

Best regards,

Rafi

**Comment by ikuyamada** [comment]
Thank you for your reply! Please reopen the issue if you face further issues.
