### ISSUE TITLE
Pre-train Corpus

### ISSUE THREAD

**Issue by Wangpeiyi9979** [studio-ousia/luke#72]
Hi, thanks for your nice work.
The `enwiki_20181220_redirects.pkl` in this [link](https://drive.google.com/file/d/129tDJ3ev6IdbJiKOmO6GTgNANunhO_vt/view?usp=sharing) is used in the paper,  and the other two files are not used, right?

**Comment by ikuyamada** [comment]
Hi, thank you for opening the issue.

We do not currently publicize the dataset used in our pretraining. Please refer to [this issue](https://github.com/studio-ousia/luke/issues/41) to build the dataset.

**Comment by Wangpeiyi9979** [comment]
Thanks!!!
