### ISSUE TITLE
Could you please release a requirements.txt?

### ISSUE THREAD

**Issue by AQA6666** [studio-ousia/luke#73]
My envirment can't install poetry.could you please release a requirements list,which can make it easy to use normal tools?

**Comment by ikuyamada** [comment]
@AQA6666  I've just uploaded requirements.txt generated by running `poetry export -f requirements.txt > requirements.txt`. Please let me know if there are further issues.

**Comment by AQA6666** [comment]
Thank you very much for your prompt reply.I just installed the environment successfully.However,I still have some questions.I want to download the OpenEntity dataset and click the  Dataset: Link to https://github.com/thunlp/ERNIE,but I can't find dataset download link in this page.Could you please tell me how to get it?

**Comment by ikuyamada** [comment]
@AQA6666 The download link is contained in [this section](https://github.com/thunlp/ERNIE#fine-tune).

**Comment by AQA6666** [comment]
Thanks for your kindly help! I successfully run it. It is an amazing job.
