### ISSUE TITLE
Fine-tuning QA task

### ISSUE THREAD

**Issue by konstantin-Sk** [studio-ousia/luke#75]
Hello. Sorry if same question already were asked, but I wasn't able to find something similar.

If I want to fine-tune my model on custom dataset (with my .json file which have same structure as squad [training set](https://rajpurkar.github.io/SQuAD-explorer/)  do I need to use 
```
--wiki-link-db-file=enwiki_20160305.pkl \
--model-redirects-file=enwiki_20181220_redirects.pkl \
--link-redirects-file=enwiki_20160305_redirects.pkl \
```

Or I need to prepare my analouges of this?

**Comment by ikuyamada** [comment]
Hi @konstantin-Sk , thank you for opening the issue. As explained in [our paper](https://arxiv.org/abs/2010.01057), our method adopted for the reading comprehension task requires entity linking to create input entity sequence. In the SQuAD task, we use a heuristic method to extract entities from the target passages using a dictionary (corresponding to enwiki_20160305.pkl) built directly from Wikipedia. If you apply our method to a custom dataset, you need to extract entities from target passages using an entity linking method suitable for the dataset.

**Comment by konstantin-Sk** [comment]
Thank you for a fast answer @ikuyamada. I will read the paper and also I will try to train the model with default heuristic.  I think it should work, because all that I want to do is to force a model to give longer answers. (I mean that I can even can use contexts from squad train set, but with another questions/answers)

**Comment by ikuyamada** [comment]
@konstantin-Sk If the passages in your dataset are extracted from Wikipedia, the heuristic entity linking method should work. Also, the link database file (enwiki_20160305.pkl) and redirect file (enwiki_*_redirects.pkl) can be generated using `build_wiki_link_db` and `generate_redirect_file` commands, defined in [this file](https://github.com/studio-ousia/luke/blob/master/examples/reading_comprehension/main.py), respectively.

**Comment by konstantin-Sk** [comment]
Sorry, I didn't mentioned that I want to use model for QA task. Is it changes somethings?

**Comment by ikuyamada** [comment]
I understand that you are working on a question answering task since the heuristic entity linking method is adopted only in the SQuAD QA task.
