### ISSUE TITLE
Hello. I have a few questions about the pretrained LUke model you uploaded.

### ISSUE THREAD

**Issue by mabongza** [studio-ousia/luke#76]
I downloaded the pre-trained model and loaded the model's state_dict with pytorch.
After checking, it was confirmed that there were no parameters for w2e_query, e2w_query, and e2e_query of each layer. 
So, is this model the Original Attention model, not the Entity-aware Attention model?
If the Original Attention model is correct, can you also upload the Entity-aware Attention model? I would appreciate your reply.

**Comment by ikuyamada** [comment]
Hi, thank you for opening the issue. As mentioned in Section 3.4 in [our paper](https://arxiv.org/abs/2010.01057), we conducted pretraining using the vanilla self-attention mechanism and introduced the entity-aware mechanism only at the fine-tuning stage. The entity-aware query matrices (i.e., w2e, e2w, and e2e) are initialized using the query matrix of the vanilla self-attention mechanism.

**Comment by mabongza** [comment]
thank you for the detailed answer. The luke structure you proposed is simple and powerful, so I think it will help a lot in my research.

**Comment by ikuyamada** [comment]
Thanks!
