### ISSUE TITLE
Some detail questions about the code:

### ISSUE THREAD

**Issue by dalek-who** [studio-ousia/luke#77]
1. The shape of ```entity_position_ids``` is [batch_size, max_entity_num, max_span_len], it seems that ```max_entity_num``` and ```max_span_len``` are not limited by model structure, and I can set any value (as long as ```max_span_len <512```), correct?
2. During pretraining, ```max_entity_num``` doesn't have an upper bound, just depends on the longest entity sequence in the batch, correct?
3. https://github.com/studio-ousia/luke/blob/440a6365534605fa1b64063cd48de646d2dd7acd/luke/model.py#L86-L91
why ```RobertaEmbeddings``` needs ```requires_grad = False``` but ```BertEmbeddings``` doesn't need? 
4. According to the paper, ```entity_embeddings.position_embeddings``` is averaged to align a span to its context position, but why ```entity_embeddings.position_embeddings.weight``` and ```embeddings.position_embeddings``` don't share the same weight?

**Comment by ikuyamada** [comment]
Hi @dalek-who,

> The shape of entity_position_ids is [batch_size, max_entity_num, max_span_len], it seems that max_entity_num and max_span_len are not limited by model structure, and I can set any value (as long as max_span_len <512), correct?

Correct. Any values can be used for these two hyper-parameters.

> During pretraining, max_entity_num doesn't have an upper bound, just depends on the longest entity sequence in the batch, correct?

No, there is a hyper-parameter `max_entity_length` (see [here](https://github.com/studio-ousia/luke/blob/master/luke/pretraining/dataset.py#L38), which restricts the length of the entity sequence up to 128.

> why RobertaEmbeddings needs requires_grad = False but BertEmbeddings doesn't need?

Actually, this line is intended to disable weight updates on the `token_type_embeddings` layer, which is not included in the RoBERTa model (this is one of the main difference between BERT and RoBERTa). However, I recently noticed that this code did not work as intended. You can safely remove this line when using LUKE.

> According to the paper, entity_embeddings.position_embeddings is averaged to align a span to its context position, but why entity_embeddings.position_embeddings.weight and embeddings.position_embeddings don't share the same weight?

This is our design choice. As you may already know, we start the pretraining of LUKE based on the RoBERTa pretrained model. We considered that the `position_embeddings` contained in the RoBERTa model may not be suitable to represent entity spans by average pooling. However, we did not conduct any experiments to validate this.

**Comment by dalek-who** [comment]
@ikuyamada Thanks!
