### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by mgong023** [studio-ousia/luke#81]
Hi,

I'm trying to pretrain the model on a custom NER dataset. My dataset consists of text and only two entity types. I'm using the command $ python -m luke.cli pretrain <data dir> <output dir>. However, i see that the <data dir> needs a metadata.json file. I looked into luke/pretraining/dataset.py and it looked like that the functions are written for a wikipedia dataset? So i dont really understand how i can train this on my own data. I also want to know what the structure of the metadata.json looks like.

**Comment by ikuyamada** [comment]
I am not sure that I understand your question correctly, but the pretraining of LUKE should be performed on Wikipedia. Maybe it is possible to support the corpus other than WIkipedia by modifying the pretraining code, but the corpus should be large and contain entity links (not entity type annotations). If you intend to fine-tune LUKE using your custom NER dataset, please refer to [this example](https://github.com/studio-ousia/luke/tree/master/examples/ner).

**Comment by mgong023** [comment]
Thanks for your answer! My bad, i got a little confused by the other issue. I indeed meant that i want to fine-tune it on my custom dataset. I saw in this [file](https://github.com/studioousia/luke/blob/00a931214780c34e5e5ed48990214beb086a3351/examples/ner/utils.py) the class `CoNLLProcessor`. I assume i need to rewrite  `_read_data` so that it can properly load my dataset. So, I would like to know what the structure of the input file should be.

**Comment by ikuyamada** [comment]
The CoNLL-2003 dataset is publicly available. Please refer to the [official web page](https://www.clips.uantwerpen.be/conll2003/ner/) for its details.

**Comment by mgong023** [comment]
Thanks! I almost got it working now. What does --fp16 do?

**Comment by ikuyamada** [comment]
If you use the option, the fine-tuning is performed using half or mixed precision based on the Apex library.

**Comment by mgong023** [comment]
I changed my dataset to the same structure of ConLL. However, i get the following error: /examples/ner/utils.py", line 239, in convert_examples_to_features `assert not entity_labels`. I printed the entity_labels: {(38, 42): 1, (46, 47): 2, (51, 55): 1, (61, 62): 2}, but it should be empty. I dont understand how it got filled. Is there an error in my dataset?

**Comment by ikuyamada** [comment]
I am sorry, but since we do not officially support custom datasets, we do not support errors occurred using such datasets.
