### ISSUE TITLE
Is there any plan to release huggingface notebook for Question Answering task?

### ISSUE THREAD

**Issue by Nardien** [studio-ousia/luke#82]
Thank you for great work and I really appreciate that the LUKE is now available on huggingface transformers library!

I just wonder whether you have the plan to release huggingface example (notebook) for QA task using LUKE or not.

Do you have any plan?

**Comment by ikuyamada** [comment]
Hi, thank you for opening the issue!
Currently, we do not have a plan to do it. However, we intend to refactor the existing fine-tuning code to use HuggingFace library with a recent framework (e.g., AllenNLP and PyTorch lightning), and we may do it in the near future.

**Comment by Nardien** [comment]
Thank you for your response. I look forward to seeing it :)
