### ISSUE TITLE
Question About Tweaking Output Shape When Trying Luke-Large

### ISSUE THREAD

**Issue by yuxinxu77** [studio-ousia/luke#84]
Our team is currently running Luke-Large and want to fine-tune it on our ner dataset. We want to make the output shape to be (batch size, 50, 18), given that ideally each sentence contains 50 words, and each word get assigned one of the 18 possible classes. So far, it turns out that Luke-Large can only output (batch size, 32, 18). Is there a way that we can tweak it into the shape we want, or is this just not possible given 32 is the official output shape of the embeddings?

**Comment by ikuyamada** [comment]
Hi, I have no idea why the sequence length becomes 32 if the input sequence length is 50. Maybe it is related to our padding implementation: our code performs padding based on the maximum sequence length in instances in each batch.
https://github.com/studio-ousia/luke/blob/master/examples/ner/main.py#L193

**Comment by yuxinxu77** [comment]
> Hi, I have no idea why the sequence length becomes 32 if the input sequence length is 50. Maybe it is related to our padding implementation: our code performs padding based on the maximum sequence length in instances in each batch.
> https://github.com/studio-ousia/luke/blob/master/examples/ner/main.py#L193

Thanks for the suggestion! Now the padding issue's resolved!
