### ISSUE TITLE
How to fine-tune model for Relation Classification  to be used in the transformers library?

### ISSUE THREAD

**Issue by gchlodzinski** [studio-ousia/luke#87]
Hi,

I tried to fine-tune model for Relation Classification and use it for inference in the transformers library.
I created model folder by combining fine-tuned model binary file and + other config files required by the transformers library.

It crashes, most likely due to the incorrect entity_vocal_size param:
- When I fine tune it using this repo, entity_vocab_size is set to 3
- When I use LukeTokenizer it generates entity_ids tensor set to [2,3] which exceeds entity embedding dimension
- Strangely finetuned model available from huggingface https://huggingface.co/studio-ousia/luke-large-finetuned-tacred/blob/main/config.json has entity_vocab_size set to 500000
- Unfortunately I cannot set this value (500000) when fine-tuning since it crashes fine-tuning process

Could you provide instruction or hints on the entity_vocab_size param or general process?

Thanks,
Grzeorz

**Comment by ikuyamada** [comment]
Hi @gchlodzinski,

We do not currently provide fine-tuning code that is based on the model implementation in the transformers library. The checkpoint file available in the huggingface's model hub is converted using [this script](https://gist.github.com/ikuyamada/2ef87bd24ca7d6c0581c6221caf190e0) with the files contained in the [model file](https://drive.google.com/file/d/1S7smSBELcZWV7-slfrb94BKcSCCoxGfL/view?usp=sharing) and [fine-tuned checkpoint file](https://drive.google.com/file/d/10XSaQRtQHn13VB_6KALObvok6hdXw7yp/view?usp=sharing).

**Comment by gchlodzinski** [comment]
Hi @ikuyamada,

Thank you so much for providing the script. It worked well and I was able to convert my fine-tuned model.
I used my custom dataset during fine tuning, currently supporting only 3 types of relations.
And besides obvious modifications to the script I had to comment out the following assertions in my case
```
assert len(missing_keys) == 1 and missing_keys[0] == "luke.embeddings.position_ids"    
assert not unexpected_keys
```
since `missing_keys` in case of my model was empty. But still converted model worked well in the transformers library.

**Comment by fillipefbr** [comment]
Hello, 

I'm also trying to run this script to use a fine-tuned model with the Transformers library but I got the following error:

```
File "convert_tacred_checkpoint.py", line 95, in convert_luke_checkpoint
    missing_keys, unexpected_keys = model.load_state_dict(new_state_dict, strict=False)
  File "C:\Users\admin\anaconda3\envs\luke\lib\site-packages\torch\nn\modules\module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for LukeForEntityPairClassification:
        size mismatch for classifier.weight: copying a param with shape torch.Size([33, 1536]) from checkpoint, the shape in current model is torch.Size([32, 1536])
```

My custom dataset is composed of 32 relations. Removing the following lines ignores the error:

```
missing_keys, unexpected_keys = model.load_state_dict(new_state_dict, strict=False)
assert len(missing_keys) == 1 and missing_keys[0] == "luke.embeddings.position_ids"
assert not unexpected_keys
```

However, the generated model doesn't work as expected, it only predicts the same relation for any given entity pair...

@gchlodzinski, did you face a similar problem?

**Comment by ikuyamada** [comment]
@fillipefbr  It looks like your dataset actually contains 33 relations instead of 32. Please confirm that `label_list`, created at the following line, consists only of 32 relations in your dataset.
https://github.com/studio-ousia/luke/blob/master/examples/relation_classification/main.py#L183

**Comment by gchlodzinski** [comment]
@fillipefbr I looked at my modified code and indeed I have commented out asserts so most likely I had similar problems.  And what @ikuyamada wrote might help to resolve the issue (in a better way than commenting out).
But despite commenting assertions out my models trained on a custom dataset worked correctly. I trained LUKE several times on different datasets, converted  it to transformers format and it was working with expected performance.

**Comment by fillipefbr** [comment]
@ikuyamada, @gchlodzinski thank you for your feedback! 
It turns out [this line](https://github.com/studio-ousia/luke/blob/master/examples/relation_classification/utils.py#L59) was adding a `no_relation` label to the dataset, which doesn't exist in my application. Modifying the generated `label_list` (as pointed by @ikuyamada) and retraining the model solved the issue. Now eveything works as expected!
