### ISSUE TITLE
Could you please tell me that when will you release luke-large model for transformers?

### ISSUE THREAD

**Issue by AQA6666** [studio-ousia/luke#89]
Or could you please tell me how can I get luke-tokenizer, luke-large model to complete down-stream task using current released file? LUKE is a great work , and base version has helped our research a lot, so we are sincerely looking forward to the large version, or to use current released file to get luke-large, but there is a lack of help documentation and it is hard to read code with few code annotation.

**Comment by ikuyamada** [comment]
Hi @AQA6666,
I may not be misunderstand your question, but there are already the model checkpoint files of luke-large available on the model hub:
https://huggingface.co/models?search=luke-large

**Comment by AQA6666** [comment]
> Hi @AQA6666,
> I may misunderstand your question, but there are already the model checkpoint files of luke-large available on the model hub:
> https://huggingface.co/models?search=luke-large

Sorry, I may be mislead by the official doc's example, which makes me think that there is only base version in transformers.Thanks for your reply!
