### ISSUE TITLE
Question: (Huggingface API) Classification Loss for transformers.LukeForEntitySpanClassification

### ISSUE THREAD

**Issue by zhenbangt** [studio-ousia/luke#90]
In transformers.LukeForEntitySpanClassification, the loss is calculated from labels of shape `(batch_size, entity_length)` and in range `[0, ..., config.num_labels - 1]`. I did not see in the source code you masked out the loss for padded tokens, nor did you make a special label for padded tokens. So how do you deal with the loss of padded sequences?

Many thanks!

**Comment by ikuyamada** [comment]
Hi @zhenbangt,

I believe this is an issue in the `LukeForEntitySpanClassification` head model. But please file an issue to the huggingface repository since this repository does not contain the corresponding code.
