### ISSUE TITLE
Unmasking and random word in MLM

### ISSUE THREAD

**Issue by asgerius** [studio-ousia/luke#93]
Hi

I have a question regarding the unmasking and random word replacement in the pretraining. Given a list of indices of masked words, the following function unmasks some of them with a given probability and replaces other with a random word ID.
However, this should happen on a per-word basis rather than be the same for the entire sequence, so should `p` not be generated for every index, that is inside the for loop? Right now, as I understand the code at least, unmasking/random word replacement either happens or not for the entire sequence of masked words rather than on a word by word basis.

Thanks for the help in advance.

```py
def perform_masking(indices: List[int]):
    p = random.random()
    for index in indices:
        masked_lm_labels[index] = output_word_ids[index]
        if p < (1.0 - self._random_word_prob - self._unmasked_word_prob):
            output_word_ids[index] = self._mask_id
        elif p < (1.0 - self._unmasked_word_prob):
            output_word_ids[index] = random.randint(self._pad_id + 1, self._tokenizer.vocab_size - 1)
```

Function taken from here: https://github.com/studio-ousia/luke/blob/master/luke/pretraining/batch_generator.py#L160

**Comment by ikuyamada** [comment]
Hi @asgerius,

This function takes `indices` argument which is a list containing subword indices corresponding to a single word (not entire sequence). When we mask a word containing multiple subwords and `whole_word_masking` is set to True, we use the same strategy for all subwords.

**Comment by asgerius** [comment]
Yes, that makes perfect sense. Thanks for clearinng up my confusion :)
