### ISSUE TITLE
about inference speed

### ISSUE THREAD

**Issue by cedar33** [studio-ousia/luke#96]
It seems that the inference speed is extremely low when I use luke to do name entity task, on single nvidia 1080ti, the speed is 30 s/batch with batch_size 32. Is there an efficient way to improve inference speed?

**Comment by ikuyamada** [comment]
Since the NER model of LUKE adopts a span-based approach (i.e., classifying all possible spans in a text) rather than sequece labeling approach, it requires longer inference time. One easy approach is reducing `max_mention_length` to limit the number of possible spans.

**Comment by cedar33** [comment]
> Since the NER model of LUKE adopts a span-based approach (i.e., classifying all possible spans in a text) rather than a sequence labeling approach, it typically requires longer inference time. One easy approach is reducing [`max_mention_length`](https://github.com/studio-ousia/luke/blob/master/examples_allennlp/ner/reader.py#L68) to limit the number of possible spans.
> 

thx

**Comment by binhna** [comment]
> Since the NER model of LUKE adopts a span-based approach (i.e., classifying all possible spans in a text) rather than a sequence labeling approach, it typically requires a longer inference time. One easy approach is reducing [`max_mention_length`](https://github.com/studio-ousia/luke/blob/master/examples_allennlp/ner/reader.py#L68) to limit the number of possible spans.

Well, If you reduce the `max_mention_length` or `max_entity_length` it might never get to the entity if it's at the end of the sentence. Let's imagine I have a sentence with 20 tokens, and the entity is the last 2 tokens. Then I need to loop 209 steps to get to that entity. So if you set it under 209, all the samples will be negative (samples with all tags are `O`)

Besides, following the code in `examples/ner` produces many negative samples (samples with all `O` tags) with the long sequence and few entities in the sequence.
