### ISSUE TITLE
  I want to know if I finetuning the model and evaluate it on another QA corpus，need I to make the link files by myself?

### ISSUE THREAD

**Issue by XY2323819551** [studio-ousia/luke#97]
Hi, sorry bother to you!  I want to know if I finetuning the model and evaluate it on another QA corpus，need I to make the link files by myself?
--wiki-link-db-file=enwiki_20160305.pkl 
--model-redirects-file=enwiki_20181220_redirects.pkl
--link-redirects-file=enwiki_20160305_redirects.pkl

if yes, what should I do?  Looking forward to your reply!

**Comment by ikuyamada** [comment]
You need to extract entities from the target passages if you apply the LUKE's QA model to another corpus. If the target paragraphs are obtained from Wikipedia, we can extract entities based on the heuristics described in the original paper (Appendix C). The heuristic approach requires files including `wiki_link_db_file`, `model_redirects_file`, and `link_redirects_file`.
